const K="juta_events_admin_v1";let events=JSON.parse(localStorage.getItem(K)||"[]"),poster="";
const $=s=>document.querySelector(s), modal=$("#modal");
function save(){localStorage.setItem(K,JSON.stringify(events));render()}
function openEdit(e){modal.classList.add("open");$("#title").textContent=e?"Edit event":"Add event";$("#id").value=e?.id||"";$("#name").value=e?.name||"";$("#date").value=e?.date||"";$("#time").value=e?.time||"20:00";$("#location").value=e?.location||"The Juta River · Giyani";$("#desc").value=e?.desc||"";$("#link").value=e?.link||"";poster=e?.poster||"";$("#preview").innerHTML=poster?`<img src="${poster}">`:"No poster selected"}
$("#add").onclick=()=>openEdit();$("#close").onclick=()=>modal.classList.remove("open");
$("#poster").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{poster=r.result;$("#preview").innerHTML=`<img src="${poster}">`};r.readAsDataURL(f)};
$("#form").onsubmit=e=>{e.preventDefault();let id=$("#id").value||crypto.randomUUID(),item={id,name:$("#name").value,date:$("#date").value,time:$("#time").value,location:$("#location").value,desc:$("#desc").value,link:$("#link").value,poster};let i=events.findIndex(x=>x.id===id);i<0?events.push(item):events[i]=item;events.sort((a,b)=>new Date(a.date+"T"+a.time)-new Date(b.date+"T"+b.time));save();modal.classList.remove("open")};
function render(){let now=new Date(),q=$("#search").value.toLowerCase(),f=$("#filter").value;let shown=events.filter(e=>{let d=new Date(e.date+"T"+e.time),ok=f==="all"||(f==="upcoming"?d>=now:d<now);return ok&&(`${e.name} ${e.location}`).toLowerCase().includes(q)});$("#total").textContent=events.length;$("#upcoming").textContent=events.filter(e=>new Date(e.date+"T"+e.time)>=now).length;let n=events.find(e=>new Date(e.date+"T"+e.time)>=now);$("#next").textContent=n?new Date(n.date+"T"+n.time).toLocaleDateString("en-ZA",{day:"2-digit",month:"short"}):"—";$("#list").innerHTML=shown.length?shown.map(e=>`<div class="row"><img src="${e.poster||"../assets/metro-home-coming.jpg"}"><div><small>${new Date(e.date+"T"+e.time).toLocaleString("en-ZA")}</small><h3>${esc(e.name)}</h3><p>${esc(e.location)} ${e.desc?"· "+esc(e.desc):""}</p></div><div><button onclick="edit('${e.id}')">Edit</button> <button class="del" onclick="del('${e.id}')">Delete</button></div></div>`).join(""):"<p style='color:#666;text-align:center;padding:40px'>No events yet.</p>"}
function esc(s=""){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
window.edit=id=>openEdit(events.find(e=>e.id===id));window.del=id=>{if(confirm("Delete this event?")){events=events.filter(e=>e.id!==id);save()}};$("#search").oninput=render;$("#filter").onchange=render;render();